"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import sys
from setuptools import setup

sys.setrecursionlimit(5000)
# python setup.py py2app
# ./dist/main.app/Contents/MacOS/main
APP = ['main.py']
# APP = ['test.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': False,
    'plist': {
        'LSUIElement': True,
    },
    'packages': ['rumps', 'zlib'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'llama-cpp-python'],
)
